# Use the official debian 9 mage
FROM ubuntu:bionic

# Set maintainer email address
LABEL maintainer="mboglesby@gmail.com"

# Install dependencies
USER root
RUN apt-get update
RUN apt-get install -y firefox \
	python3 \
	python3-pip \
	wget \
	xvfb
RUN pip3 install -U pip selenium pyvirtualdisplay
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz && \
tar -zxvf geckodriver-v0.23.0-linux64.tar.gz && \
mv ./geckodriver /usr/local/bin/

# Copy payment script and supporting files
RUN mkdir /root/tocpay
COPY *.py /root/tocpay/

# Set entrypoint command and default parameters
ENTRYPOINT ["python3", "/root/tocpay/town_of_cary_payment.py"]
CMD ["--help"]
