# Use the official ubuntu bionic image
FROM ubuntu:bionic

# Set maintainer email address
LABEL maintainer="mboglesby@gmail.com"

# Install dependencies
USER root
ENV DEBIAN_FRONTEND="noninteractive" TZ="America/New_York"
RUN apt-get update && \
	apt-get install -y python3 \
	python3-pip \
	wget \
	unzip
RUN pip3 install -U pip selenium
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
	apt-get install -y ./google-chrome-stable_current_amd64.deb
RUN wget https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip && \
	unzip ./chromedriver_linux64.zip && \
	mv ./chromedriver /usr/local/bin/

# Copy payment script and supporting files
RUN mkdir /root/tocpay
COPY *.py /root/tocpay/

# Set entrypoint command and default parameters
ENTRYPOINT ["python3", "/root/tocpay/town_of_cary_payment.py"]
CMD ["--help"]
